"""Export this synthetic checkpoint as standalone Java constants and parity tests.

No Android API dependency or guessed real-phone feature extraction. Regenerates
only TrainedPolicy.java and TrainedPolicyTest.java. Run from any directory.
"""

from pathlib import Path
import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile

from cli import DEFAULT_MODEL, load_artifact
from policy import FEATURES, dataset_manifest, generate_data

PROJECT = Path(__file__).resolve().parents[2]
PACKAGE = "dev/focuspilot/prototype"
MAIN = PROJECT / "prototype/android/app/src/main/java" / PACKAGE / "TrainedPolicy.java"
TEST = PROJECT / "prototype/android/app/src/test/java" / PACKAGE / "TrainedPolicyTest.java"


def array(values):
    return "{" + ", ".join(repr(float(value)) for value in values) + "}"


JAVA = '''package dev.focuspilot.prototype;

/**
 * Generated by prototype/policy/export_java.py from a trained synthetic checkpoint.
 * Pre-event research, 2026-10-02. Not an LLM or a learned real productivity policy.
 * Risk features are synthetic dimensionless [0,1] values. No phone observations
 * are inferred here: reopening/deferred-nudge inputs must not be fabricated.
 * Pause, consent, focus state, cooldown and freshness gates belong to the caller;
 * this pure sandbox evaluator never monitors, executes an action or debits money.
 */
public final class TrainedPolicy {
{{CONSTANTS}}
    private TrainedPolicy() {}

    public static String[] featureNames() { return FEATURE_NAMES.clone(); }

    public static final class Evaluation {
        /** Sigmoid score for the invented teacher, not real-world calibrated risk. */
        public final double score;
        public final double logit;
        public final double outputBias;
        private final double[] features, preactivations, activations, contributions;
        private final double[] ablationScores, ablationDrops, suppressedUnitScores;

        private Evaluation(double[] features, Pass pass, double[] ablationScores) {
            this.features = features.clone();
            score = pass.score;
            logit = pass.logit;
            outputBias = OUTPUT_BIAS;
            preactivations = pass.preactivations.clone();
            activations = pass.activations.clone();
            contributions = pass.contributions.clone();
            this.ablationScores = ablationScores.clone();
            ablationDrops = new double[6];
            suppressedUnitScores = new double[8];
            for (int i = 0; i < 6; i++) ablationDrops[i] = score - ablationScores[i];
            for (int j = 0; j < 8; j++) suppressedUnitScores[j] = sigmoid(logit - contributions[j]);
        }
        public double[] features() { return features.clone(); }
        public double[] hiddenPreactivations() { return preactivations.clone(); }
        public double[] hiddenActivations() { return activations.clone(); }
        /** Exact additive contributions before sigmoid; outputBias + sum = logit. */
        public double[] hiddenContributions() { return contributions.clone(); }
        /** Full recomputations with one feature set to zero; not additive attribution. */
        public double[] featureAblationScores() { return ablationScores.clone(); }
        public double[] featureAblationDrops() { return ablationDrops.clone(); }
        /** Counterfactual score with one hidden activation clamped to zero. */
        public double[] suppressedHiddenScores() { return suppressedUnitScores.clone(); }
    }

    /** Pure evaluation, including feature ablations; policy gates must be external. */
    public static Evaluation evaluate(double[] features) {
        double[] x = validate(features);
        Pass pass = forward(x);
        double[] ablations = new double[6];
        for (int i = 0; i < 6; i++) {
            double[] changed = x.clone();
            changed[i] = 0.0;
            ablations[i] = forward(changed).score;
        }
        return new Evaluation(x, pass, ablations);
    }

    /** Change one explicit sandbox feature; never substitutes missing phone data. */
    public static Evaluation intervene(double[] features, int featureIndex, double value) {
        if (featureIndex < 0 || featureIndex >= 6) throw new IllegalArgumentException("Invalid feature index");
        double[] changed = validate(features);
        changed[featureIndex] = value;
        return evaluate(changed);
    }

    private static double[] validate(double[] features) {
        if (features == null || features.length != 6)
            throw new IllegalArgumentException("Exactly six explicit synthetic features are required");
        for (double value : features) {
            if (!Double.isFinite(value) || value < 0.0 || value > 1.0)
                throw new IllegalArgumentException("Features must be finite values in [0,1]");
        }
        return features.clone();
    }

    private static final class Pass {
        final double[] preactivations = new double[8];
        final double[] activations = new double[8];
        final double[] contributions = new double[8];
        double logit, score;
    }

    private static Pass forward(double[] features) {
        Pass result = new Pass();
        double contributionSum = 0.0;
        for (int j = 0; j < 8; j++) {
            double sum = 0.0;
            for (int i = 0; i < 6; i++) sum += INPUT_WEIGHTS[j][i] * features[i];
            result.preactivations[j] = sum + HIDDEN_BIASES[j];
            result.activations[j] = Math.max(0.0, result.preactivations[j]);
            result.contributions[j] = OUTPUT_WEIGHTS[j] * result.activations[j];
            contributionSum += result.contributions[j];
        }
        result.logit = OUTPUT_BIAS + contributionSum;
        result.score = sigmoid(result.logit);
        return result;
    }

    private static double sigmoid(double value) {
        if (value >= 0.0) return 1.0 / (1.0 + Math.exp(-value));
        double exponential = Math.exp(value);
        return exponential / (1.0 + exponential);
    }
}
'''

TEST_JAVA = '''package dev.focuspilot.prototype;

import org.junit.Test;
import java.util.Random;
import static org.junit.Assert.*;

/** Generated Python held-out reference fixtures, not hand-invented expected scores. */
public class TrainedPolicyTest {
{{FIXTURES}}
    @Test public void matchesPythonHeldoutReference() {
        for (int i = 0; i < FIXTURE_FEATURES.length; i++) {
            TrainedPolicy.Evaluation result = TrainedPolicy.evaluate(FIXTURE_FEATURES[i]);
            assertEquals("score fixture " + i, FIXTURE_SCORES[i], result.score, 1e-12);
            assertEquals("logit fixture " + i, FIXTURE_LOGITS[i], result.logit, 1e-10);
            assertEquals(FIXTURE_SCORES[i] >= TrainedPolicy.DEV_THRESHOLD,
                         result.score >= TrainedPolicy.DEV_THRESHOLD);
        }
    }

    @Test public void matchesPythonContributionsAndFeatureAblations() {
        TrainedPolicy.Evaluation result = TrainedPolicy.evaluate(FIXTURE_FEATURES[2]);
        assertArrayEquals(REFERENCE_CONTRIBUTIONS, result.hiddenContributions(), 1e-10);
        assertArrayEquals(REFERENCE_ABLATIONS, result.featureAblationScores(), 1e-12);
        double total = result.outputBias;
        for (double contribution : result.hiddenContributions()) total += contribution;
        assertEquals(result.logit, total, 1e-12);
        double[] drops = result.featureAblationDrops();
        for (int i = 0; i < 6; i++) {
            assertEquals(result.score - REFERENCE_ABLATIONS[i], drops[i], 1e-12);
            assertTrue(drops[i] >= -1e-12);
        }
    }

    @Test public void isMonotonicAcrossSampledRiskIncreases() {
        Random random = new Random(9);
        for (int trial = 0; trial < 300; trial++) {
            double[] features = new double[6];
            for (int i = 0; i < 6; i++) features[i] = random.nextDouble();
            double score = TrainedPolicy.evaluate(features).score;
            for (int i = 0; i < 6; i++) {
                double increased = features[i] + random.nextDouble() * (1.0 - features[i]);
                assertTrue(TrainedPolicy.intervene(features, i, increased).score >= score - 1e-12);
            }
        }
    }

    @Test public void rejectsMalformedAndUnboundedFeatures() {
        assertThrows(IllegalArgumentException.class, () -> TrainedPolicy.evaluate(null));
        assertThrows(IllegalArgumentException.class, () -> TrainedPolicy.evaluate(new double[5]));
        for (double invalid : new double[]{Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, -0.1, 1.1}) {
            double[] features = new double[6]; features[3] = invalid;
            assertThrows(IllegalArgumentException.class, () -> TrainedPolicy.evaluate(features));
        }
        assertThrows(IllegalArgumentException.class, () -> TrainedPolicy.intervene(new double[6], 6, 0.5));
        assertThrows(IllegalArgumentException.class, () -> TrainedPolicy.intervene(new double[6], 0, -0.1));
    }

    @Test public void resultAndFeatureNamesAreDefensiveCopies() {
        double[] features = FIXTURE_FEATURES[0].clone();
        TrainedPolicy.Evaluation original = TrainedPolicy.evaluate(features);
        double score = original.score;
        features[0] = 1.0 - features[0];
        assertEquals(FIXTURE_FEATURES[0][0], original.features()[0], 0.0);
        double[] contributions = original.hiddenContributions(); contributions[0] = -1000;
        assertTrue(original.hiddenContributions()[0] >= 0.0);
        String[] names = TrainedPolicy.featureNames(); names[0] = "mutated";
        assertEquals("selected_app_budget_overrun", TrainedPolicy.featureNames()[0]);
        assertEquals(score, TrainedPolicy.evaluate(FIXTURE_FEATURES[0]).score, 0.0);
    }

    @Test public void hiddenSuppressionCannotRaiseSyntheticRisk() {
        for (double[] features : FIXTURE_FEATURES) {
            TrainedPolicy.Evaluation result = TrainedPolicy.evaluate(features);
            for (double counterfactual : result.suppressedHiddenScores())
                assertTrue(counterfactual <= result.score + 1e-12);
        }
    }
}
'''


PROBE = '''import dev.focuspilot.prototype.TrainedPolicy;
import java.io.BufferedReader;
import java.io.InputStreamReader;
public class PolicyParityProbe {
    public static void main(String[] args) throws Exception {
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        String line;
        while ((line = input.readLine()) != null) {
            String[] values = line.split(",");
            double[] features = new double[6];
            for (int i = 0; i < 6; i++) features[i] = Double.parseDouble(values[i]);
            TrainedPolicy.Evaluation result = TrainedPolicy.evaluate(features);
            StringBuilder row = new StringBuilder();
            row.append(result.score).append(" ").append(result.logit);
            for (double value : result.hiddenContributions()) row.append(" ").append(value);
            for (double value : result.featureAblationScores()) row.append(" ").append(value);
            System.out.println(row);
        }
    }
}
'''


def verify_export(model, artifact, rows, java_home):
    javac = str(java_home / "bin/javac") if java_home else shutil.which("javac")
    java = str(java_home / "bin/java") if java_home else shutil.which("java")
    if not javac or not java:
        raise RuntimeError("JDK required for --verify; supply --java-home or set PATH")
    version = subprocess.run([javac, "-version"], check=True, capture_output=True, text=True)
    with tempfile.TemporaryDirectory(prefix="focuspilot-java-parity-") as directory:
        probe = Path(directory) / "PolicyParityProbe.java"
        probe.write_text(PROBE)
        subprocess.run([javac, "-d", directory, str(MAIN), str(probe)], check=True)
        vectors = "\n".join(",".join(repr(value) for value in row.features) for row in rows) + "\n"
        output = subprocess.run([java, "-cp", directory, "PolicyParityProbe"], input=vectors,
                                capture_output=True, text=True, check=True).stdout.splitlines()
    if len(output) != len(rows):
        raise ValueError("Java parity output row count mismatch")
    maximum = {"score": 0.0, "logit": 0.0, "hidden_contributions": 0.0, "feature_ablation_scores": 0.0}
    disagreements = 0
    threshold = artifact["training"]["threshold"]
    for row, line in zip(rows, output):
        values = [float(value) for value in line.split()]
        if len(values) != 16:
            raise ValueError("Java parity output width mismatch")
        reference = model.inspect(row.features)
        maximum["score"] = max(maximum["score"], abs(values[0] - reference["probability"]))
        maximum["logit"] = max(maximum["logit"], abs(values[1] - reference["logit"]))
        maximum["hidden_contributions"] = max(maximum["hidden_contributions"], *[
            abs(value - unit["logit_contribution"]) for value, unit in zip(values[2:10], reference["hidden_units"])])
        maximum["feature_ablation_scores"] = max(maximum["feature_ablation_scores"], *[
            abs(value - ablation["probability_after"]) for value, ablation in zip(values[10:], reference["feature_ablations"])])
        disagreements += (values[0] >= threshold) != (reference["probability"] >= threshold)
    if (maximum["score"] > 1e-12 or maximum["feature_ablation_scores"] > 1e-12
            or maximum["logit"] > 1e-10 or maximum["hidden_contributions"] > 1e-10 or disagreements):
        raise ValueError(f"Export parity failed: {maximum}, disagreements={disagreements}")
    report = {
        "status": "verified standalone desktop JVM, not physical phone/NPU execution",
        "command": "python3 prototype/policy/export_java.py --verify",
        "heldout_count": len(rows), "heldout_scenario_families": artifact["dataset"]["holdout"]["families"],
        "maximum_absolute_difference": maximum, "threshold_disagreements": disagreements,
        "threshold": threshold, "javac": (version.stdout + version.stderr).strip(),
        "source_sha256": artifact["implementation_sha256"],
        "parameters_sha256": artifact["parameters_sha256"],
        "generated_java_sha256": hashlib.sha256(MAIN.read_bytes()).hexdigest(),
    }
    destination = Path(__file__).parent / "java-export-results.json"
    destination.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="Compile exported class and compare all480 heldout vectors")
    parser.add_argument("--java-home", type=Path, help="Optional JDK root, otherwise use java/javac on PATH")
    args = parser.parse_args()
    artifact, model = load_artifact(DEFAULT_MODEL)
    source_hash = hashlib.sha256((Path(__file__).parent / "policy.py").read_bytes()).hexdigest()
    if source_hash != artifact["implementation_sha256"]:
        raise ValueError("Policy implementation differs from trained checkpoint provenance")
    config = artifact["training"]
    splits = generate_data(config["seed"], config["per_family"])
    if dataset_manifest(splits) != artifact["dataset"]:
        raise ValueError("Dataset differs from checkpoint")
    p = model.parameters
    constants = [
        f"    public static final int PARAMETER_COUNT = {artifact['parameter_count']};",
        f"    public static final int TRAINING_SEED = {config['seed']};",
        f"    public static final int SELECTED_EPOCH = {config['selected_epoch']};",
        f"    public static final double DEV_THRESHOLD = {config['threshold']};",
        f"    public static final String SOURCE_SHA256 = {json.dumps(source_hash)};",
        f"    public static final String PARAMETERS_SHA256 = {json.dumps(artifact['parameters_sha256'])};",
        f"    public static final String CHECKPOINT_SHA256 = {json.dumps(hashlib.sha256(DEFAULT_MODEL.read_bytes()).hexdigest())};",
        '    public static final String PROVENANCE = "65-parameter network trained on invented synthetic teacher labels; no real productivity or LLM interpretation";',
        '    private static final String[] FEATURE_NAMES = {' + ', '.join(json.dumps(f) for f in FEATURES) + '};',
        "    private static final double[][] INPUT_WEIGHTS = {",
        *["        " + array(row) + "," for row in p["input_weights"]],
        "    };",
        "    private static final double[] HIDDEN_BIASES = " + array(p["hidden_biases"]) + ";",
        "    private static final double[] OUTPUT_WEIGHTS = " + array(p["output_weights"]) + ";",
        f"    private static final double OUTPUT_BIAS = {repr(p['output_bias'])};",
    ]
    fixtures = []
    for family in artifact["dataset"]["holdout"]["families"]:
        rows = [r for r in splits["holdout"] if r.family == family]
        fixtures += [min(rows, key=lambda r: model.probability(r.features)),
                     max(rows, key=lambda r: model.probability(r.features)),
                     min(rows, key=lambda r: abs(model.probability(r.features) - config["threshold"]))]
    reference = model.inspect(fixtures[2].features)
    fixture_code = ["    // Min/max/nearest-threshold examples per held-out scenario family.",
                    "    private static final double[][] FIXTURE_FEATURES = {",
                    *["        " + array(row.features) + ", // " + row.family for row in fixtures],
                    "    };",
                    "    private static final double[] FIXTURE_SCORES = " + array([model.probability(r.features) for r in fixtures]) + ";",
                    "    private static final double[] FIXTURE_LOGITS = " + array([model.forward(r.features)[2] for r in fixtures]) + ";",
                    "    private static final double[] REFERENCE_CONTRIBUTIONS = " + array([u["logit_contribution"] for u in reference["hidden_units"]]) + ";",
                    "    private static final double[] REFERENCE_ABLATIONS = " + array([a["probability_after"] for a in reference["feature_ablations"]]) + ";"]
    MAIN.parent.mkdir(parents=True, exist_ok=True)
    TEST.parent.mkdir(parents=True, exist_ok=True)
    MAIN.write_text(JAVA.replace("{{CONSTANTS}}", "\n".join(constants)))
    TEST.write_text(TEST_JAVA.replace("{{FIXTURES}}", "\n".join(fixture_code)))
    summary = {"source": str(MAIN), "test": str(TEST), "fixture_count": len(fixtures),
               "parameter_sha256": artifact["parameters_sha256"], "source_sha256": source_hash}
    if args.verify:
        summary["full_holdout_export_parity"] = verify_export(model, artifact, splits["holdout"], args.java_home)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
