package dev.focuspilot.prototype;

/**
 * Generated by prototype/policy/export_java.py from a trained synthetic checkpoint.
 * Pre-event research, 2026-10-02. Not an LLM or a learned real productivity policy.
 * Risk features are synthetic dimensionless [0,1] values. No phone observations
 * are inferred here: reopening/deferred-nudge inputs must not be fabricated.
 * Pause, consent, focus state, cooldown and freshness gates belong to the caller;
 * this pure sandbox evaluator never monitors, executes an action or debits money.
 */
public final class TrainedPolicy {
    public static final int PARAMETER_COUNT = 65;
    public static final int TRAINING_SEED = 20261002;
    public static final int SELECTED_EPOCH = 100;
    public static final double DEV_THRESHOLD = 0.62;
    public static final String SOURCE_SHA256 = "52810b9e0d982d3d04cd611bb9b908ce0d69c8fde77069055d594d8ad5ce178c";
    public static final String PARAMETERS_SHA256 = "d1edaa8015959a4bd199850ef3492547363ecdd8131a824fd2bf4604062fc1a6";
    public static final String CHECKPOINT_SHA256 = "6924de782bd52944d5bf87352f9a7dd0bc1e4e0518bcd5ba04f9ea6fcffb67b8";
    public static final String PROVENANCE = "65-parameter network trained on invented synthetic teacher labels; no real productivity or LLM interpretation";
    private static final String[] FEATURE_NAMES = {"selected_app_budget_overrun", "continuous_session_overrun", "reopen_count", "active_focus_overlap", "deferred_nudges", "elapsed_time_overrun"};
    private static final double[][] INPUT_WEIGHTS = {
        {2.1305307193301615, 1.7379740087665134, 0.6560759992133103, 0.5105105344984145, 0.2871009677598251, 0.5676423441373614},
        {1.9905720205894053, 1.623369414239104, 0.5852433284218196, 0.48731976111303477, 0.2741905578202183, 0.5253614522044658},
        {2.492592175068471, 2.004723062584796, 0.73445354215641, 0.5819265125936754, 0.31362718907640424, 0.6259060689698641},
        {2.0785671184934196, 1.7150791306750686, 0.6164254194865941, 0.5012626326038636, 0.27037512211767945, 0.5471232099268053},
        {1.2538080273709749, 1.0339875900571667, 0.40002282121351745, 0.33335883255516585, 0.1813121016683017, 0.33541171770552214},
        {1.99361439810309, 1.6373867582571413, 0.60185939110299, 0.4786586763289066, 0.27154518691659296, 0.5081702285904404},
        {1.7215551666202973, 1.4533429748604003, 0.5208031857320544, 0.44297363456738814, 0.2555978899609596, 0.4379447429582178},
        {2.3912639724373563, 1.9501016228774546, 0.702772883099633, 0.5873137887280563, 0.3169433956911058, 0.6016294370639662},
    };
    private static final double[] HIDDEN_BIASES = {-2.4743536995133573, -2.3010695684249503, -2.8239634808701264, -2.4010622836687694, -1.4931551121151028, -2.3050366190614686, -2.0341060214856275, -2.74456373307918};
    private static final double[] OUTPUT_WEIGHTS = {3.160900910738326, 2.932315101361946, 3.6471265439400407, 3.0780182005632546, 1.8696309547470953, 2.9549200860609806, 2.5732936899285757, 3.5305049169512093};
    private static final double OUTPUT_BIAS = -5.8347942455574575;
    private TrainedPolicy() {}

    public static String[] featureNames() { return FEATURE_NAMES.clone(); }

    public static final class Evaluation {
        /** Sigmoid score for the invented teacher, not real-world calibrated risk. */
        public final double score;
        public final double logit;
        public final double outputBias;
        private final double[] features, preactivations, activations, contributions;
        private final double[] ablationScores, ablationDrops, suppressedUnitScores;

        private Evaluation(double[] features, Pass pass, double[] ablationScores) {
            this.features = features.clone();
            score = pass.score;
            logit = pass.logit;
            outputBias = OUTPUT_BIAS;
            preactivations = pass.preactivations.clone();
            activations = pass.activations.clone();
            contributions = pass.contributions.clone();
            this.ablationScores = ablationScores.clone();
            ablationDrops = new double[6];
            suppressedUnitScores = new double[8];
            for (int i = 0; i < 6; i++) ablationDrops[i] = score - ablationScores[i];
            for (int j = 0; j < 8; j++) suppressedUnitScores[j] = sigmoid(logit - contributions[j]);
        }
        public double[] features() { return features.clone(); }
        public double[] hiddenPreactivations() { return preactivations.clone(); }
        public double[] hiddenActivations() { return activations.clone(); }
        /** Exact additive contributions before sigmoid; outputBias + sum = logit. */
        public double[] hiddenContributions() { return contributions.clone(); }
        /** Full recomputations with one feature set to zero; not additive attribution. */
        public double[] featureAblationScores() { return ablationScores.clone(); }
        public double[] featureAblationDrops() { return ablationDrops.clone(); }
        /** Counterfactual score with one hidden activation clamped to zero. */
        public double[] suppressedHiddenScores() { return suppressedUnitScores.clone(); }
    }

    /** Pure evaluation, including feature ablations; policy gates must be external. */
    public static Evaluation evaluate(double[] features) {
        double[] x = validate(features);
        Pass pass = forward(x);
        double[] ablations = new double[6];
        for (int i = 0; i < 6; i++) {
            double[] changed = x.clone();
            changed[i] = 0.0;
            ablations[i] = forward(changed).score;
        }
        return new Evaluation(x, pass, ablations);
    }

    /** Change one explicit sandbox feature; never substitutes missing phone data. */
    public static Evaluation intervene(double[] features, int featureIndex, double value) {
        if (featureIndex < 0 || featureIndex >= 6) throw new IllegalArgumentException("Invalid feature index");
        double[] changed = validate(features);
        changed[featureIndex] = value;
        return evaluate(changed);
    }

    private static double[] validate(double[] features) {
        if (features == null || features.length != 6)
            throw new IllegalArgumentException("Exactly six explicit synthetic features are required");
        for (double value : features) {
            if (!Double.isFinite(value) || value < 0.0 || value > 1.0)
                throw new IllegalArgumentException("Features must be finite values in [0,1]");
        }
        return features.clone();
    }

    private static final class Pass {
        final double[] preactivations = new double[8];
        final double[] activations = new double[8];
        final double[] contributions = new double[8];
        double logit, score;
    }

    private static Pass forward(double[] features) {
        Pass result = new Pass();
        double contributionSum = 0.0;
        for (int j = 0; j < 8; j++) {
            double sum = 0.0;
            for (int i = 0; i < 6; i++) sum += INPUT_WEIGHTS[j][i] * features[i];
            result.preactivations[j] = sum + HIDDEN_BIASES[j];
            result.activations[j] = Math.max(0.0, result.preactivations[j]);
            result.contributions[j] = OUTPUT_WEIGHTS[j] * result.activations[j];
            contributionSum += result.contributions[j];
        }
        result.logit = OUTPUT_BIAS + contributionSum;
        result.score = sigmoid(result.logit);
        return result;
    }

    private static double sigmoid(double value) {
        if (value >= 0.0) return 1.0 / (1.0 + Math.exp(-value));
        double exponential = Math.exp(value);
        return exponential / (1.0 + exponential);
    }
}
